### ISSUE TITLE
/stats page takes long to load

### ISSUE THREAD

**Issue by terorie** [simon987/od-database#17]
How about regularly exporting and caching them so we can display them quickly?

**Comment by terorie** [comment]
Also timing out now, I think this is because the server iterates through all done tasks which is well over 500K right now to show the crawl stats table.

There are two options:
 1. __Query optimisation__: More aggressive caching of the results and SQL-side aggregation so the whole table isn't loaded into Python.
 2. __Balance table__: As all 5 columns are aggregated, the results (displayed in /stats) could be calculated server side. It would be updated every time the aggregation changes (when a new site gets crawled)
  Example pseudo code:
```js
onNewTaskDone(name, time, fileCount) {
    c = crawlers[name]
    c.totalTime += time
    c.totalCrawls++
    c.totalFileCount += fileCount
    c.avgTime = c.totalTime / c.totalCrawls
    c.avgFileCount = c.totalFileCount / c.totalCrawls
}
```

@simon987 What's your opinion?

Current table
![Table](https://media.discordapp.net/attachments/488038527372886036/541330446504558592/Bildschirmfoto_2019-02-02_um_19.50.55.png?width=1419&height=540)

**Comment by terorie** [comment]
@simon987 task manager includes the crawl stats table?

**Comment by simon987** [comment]
by 'task manager' I meant everything related to tasks, including stats
