### ISSUE TITLE
Newest captcha has both 0 and O and they're difficult to distinguish

### ISSUE THREAD

**Issue by gingerbeardman** [simon987/od-database#19]
Newest captcha has both 0 and O and they're difficult to distinguish

**Comment by simon987** [comment]
![image](https://user-images.githubusercontent.com/7120851/52185989-a24c7780-27f2-11e9-8135-ab4bf3817bc3.png)
zeroes have a bar in the middle

**Comment by gingerbeardman** [comment]
That would be why I have been failing captchas. Thanks!
