### ISSUE TITLE
Feature request: Do not display links that are 404

### ISSUE THREAD

**Issue by Wingysam** [simon987/od-database#4]
When a search is performed, do an HTTP HEAD request on each URL on the page. If the status code for the file is 404, do not show it in the results.

**Comment by terorie** [comment]
Impossible to do server side, so I'll try this in JS. Might get ugly with CORS, though.

**Comment by simon987** [comment]
I wouldn't bother. I'm not sure I would want my browser ping a bunch of random hosts without me knowing.

**Comment by terorie** [comment]
Very good argument. Doing it server side will overwhelm the DB server. So I think this can be closed?
