### ISSUE TITLE
High CPU usage in Safari due to incomplete recaptcha+CSP implementation 

### ISSUE THREAD

**Issue by gingerbeardman** [simon987/od-database#5]
For some reason the OD-DB search page really stresses out Safari.
It makes it unusable, especially when trying to do the recaptcha.

I have to use Chrome to not have my laptop fans go into overdrive.

> ProductName:	Mac OS X
> ProductVersion:	10.13.6
> BuildVersion:	17G65
> 
> ProductName:	Safari
> ProductVersion:	11.1.2
> BuildVersion:	13605.3.8
> 
> MacBook Pro (Retina, 13-inch, Early 2013)
> 3 GHz Intel Core i7
> 8 GB 1600 MHz DDR3
> macOS 10.13.6 (17G65)

**Comment by simon987** [comment]
There is very little JavaScript code executed in the search page (none at all iirc) except for:
* Bootstrap
* Size slider
* google recaptcha

I doubt that the size slider or the bootstrap code is causing this issue. Can you try to disable javascript for *.the-eye.eu with JS Blocker or similar in safari and confirm that it isn't the case?

**Comment by gingerbeardman** [comment]
This is even before I get to the page with the slider on.

Switching JS off prevents the issue.

I'll see if I can identify what exactly is the cause.

## Videos
- Safari: https://youtu.be/ekkFlSJiMII
- Chrome: https://youtu.be/ou8D1nf6fLQ

**Comment by gingerbeardman** [comment]
I'll do so shortly. 

I did try to use JSblocker but I couldn't decipher it's UI

**Comment by gingerbeardman** [comment]
OK, clue number 1 in th console log

<img width="1280" alt="screen shot 2018-10-28 at 17 48 25" src="https://user-images.githubusercontent.com/49612/47619794-63fc3980-dada-11e8-8687-cc726e5c25af.png">

**Comment by gingerbeardman** [comment]
If I prevent `https://www.google.com/recaptcha/api.js` from loading, the above errors go away and everything runs at a good speed.

It seems the issue is with recaptcha and known about https://github.com/google/google-api-javascript-client/issues/397

FWIW I use AdGuard DNS not sure that would affect recaptcha frequency?

**Comment by gingerbeardman** [comment]
Possible solution?

> I'm using Content-Security-Policy (CSP) on my website. How can I configure it to work with reCAPTCHA?
> 
> We recommend using the nonce-based approach documented with CSP3. Make sure to include your nonce in the reCAPTCHA api.js script tag, and we'll handle the rest.
> 
> Note: reCAPTCHA also works with 'strict-dynamic' on browsers that support it.
> 
> Alternatively, please add the following values to the directives:
> 
> script-src https://www.google.com/recaptcha/, https://www.gstatic.com/recaptcha/
> frame-src https://www.google.com/recaptcha/
>

**Comment by gingerbeardman** [comment]
I don't run a proxy or VPN, no. But I do run some adblockers. I'll have another look.

**Comment by gingerbeardman** [comment]
OK, I can reproduce in Safari Technology Preview (pre-release channel for devs) in which I have no extensions installed. So I doubt it's due to Safari itself.

Next, I changed tried different DNS servers, AdGuard, OpenDNS, Google. Problem persists.

Will look into the recaptcha file/include now

**Comment by gingerbeardman** [comment]
There are 7 mentions of the `nonce` attribute in the code inserted into the page by the `https://www.google.com/recaptcha/api.js` file, whose goal seems to be matching the CSP of the google server. 

As I said previously, if I block that then the errors and CPU thrashing goes away. 

So I am back to square one, I have no idea why this is a problem for Safari and not Chrome.

Is there an alternate way of including the recaptcha to see if that helps?

I'm out of ideas, for now,

**Comment by simon987** [comment]
This is how it's included:
```
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
```
as specified in https://developers.google.com/recaptcha/docs/invisible. I don't see another way to do it

**Comment by gingerbeardman** [comment]
Yes, I literally can't use the site in Safari as its so slow. Every key press or mouse click takes seconds to register.

**Comment by simon987** [comment]
I was looking for an excuse to use a FOSS captcha, this might just be it...
Everything seems to indicate the ReCAPTCHA code is causing this issue so I'll try to look for alternatives in the next few weeks.
Thank you for the help!

**Comment by gingerbeardman** [comment]
Cheers, I'll keep an eye on it

**Comment by emredalkiran** [comment]
@gingerbeardman, check [this](answer) and [Mozilla's web site](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) out. Currently, Safari does not support `strict-dynamic`.

**Comment by gingerbeardman** [comment]
@emredalkiran I'm not sure what you mean? The  issue you linked, I had already linked earlier in this thread. 

Even if Safari does not support that directive, I don't see any bad results from it on any other sites other than od-db which is the odd thing

**Comment by gingerbeardman** [comment]
Just an extra data point: https://github.com/itchio/itch/issues/2156

So I think I'll look into reporting this to google

**Comment by gingerbeardman** [comment]
I reported to this to the ReCAPTCHA team via email and it seems to have been fixed at the source code level?

Will leave issue open for a while.

**Comment by terorie** [comment]
@simon987 close dis

**Comment by gingerbeardman** [comment]
@terorie why?

**Comment by terorie** [comment]
@gingerbeardman It's not using reCAPTCHA anymore 😄

**Comment by gingerbeardman** [comment]
I see, there is a typo in the banner

> After a slight hiccup, our servers are back online!
> The project **now longer** relies on ReCaptcha, has enhanced elasticsearch configuration and is hosted on even better hardware, enjoy!

Should be _no longer_

**Comment by terorie** [comment]
Ohh good catch, I didn't even see that

**Comment by terorie** [comment]
Can you quickly do a pull request to fix it, please?
